import mongoose from "mongoose";

export const QUESTION_TYPES = [
  "mcq",
  "fill_blank",
  "true_false",
  "very_short",
  "short",
  "long",
  "assertion",
  "case",
];

export const DIFFICULTIES = ["Easy", "Medium", "Hard"];

const questionSchema = new mongoose.Schema(
  {
    board: { type: String, required: true, default: "CBSE" },
    class: { type: String, required: true },
    subject: { type: String, required: true },
    chapter: { type: String, required: true },
    topic: { type: String, default: "" },
    type: { type: String, enum: QUESTION_TYPES, required: true },
    difficulty: { type: String, enum: DIFFICULTIES, required: true, default: "Medium" },
    bloomLevel: { type: String, default: "Understanding (Level 2)" },
    marks: { type: Number, default: 1 },

    text: { type: String, required: true },
    // For mcq / assertion / case / true_false: array of option strings
    options: { type: [String], default: [] },
    // Index into options[] that is correct (mcq/assertion/true_false/case)
    correctIndex: { type: Number, default: null },
    // Human-readable canonical answer (used for short/long/fill_blank too)
    answer: { type: String, required: true },
    explanation: { type: String, default: "" },

    // "bank" = human-verified, curated question; "ai" = generated by LLM (kept for reuse/audit)
    source: { type: String, enum: ["bank", "ai"], default: "bank" },
    verified: { type: Boolean, default: true },

    // normalized text used for fast duplicate detection
    normalizedText: { type: String, index: true },

    tags: { type: [String], default: [] },

    // Optional semantic-search vector. Populated lazily by the retrieval
    // service so existing question-bank data does not need a migration.
    embedding: { type: [Number], default: undefined, select: false },
  },
  { timestamps: true }
);

questionSchema.index({ board: 1, class: 1, subject: 1, chapter: 1, type: 1, difficulty: 1 });

questionSchema.pre("save", function (next) {
  this.normalizedText = normalize(this.text);
  next();
});

export function normalize(str = "") {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, " ")
    .trim();
}

export default mongoose.model("Question", questionSchema);
